# AlertManager configuration for MyRepETL

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@myrepetl.local'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        severity: info
      receiver: 'info-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/'

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/critical'
    # Uncomment and configure for email alerts
    # email_configs:
    #   - to: 'admin@company.com'
    #     subject: 'CRITICAL: MyRepETL Alert'
    #     body: |
    #       {{ range .Alerts }}
    #       Alert: {{ .Annotations.summary }}
    #       Description: {{ .Annotations.description }}
    #       {{ end }}

  - name: 'warning-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/warning'
    # Uncomment and configure for email alerts
    # email_configs:
    #   - to: 'admin@company.com'
    #     subject: 'WARNING: MyRepETL Alert'
    #     body: |
    #       {{ range .Alerts }}
    #       Alert: {{ .Annotations.summary }}
    #       Description: {{ .Annotations.description }}
    #       {{ end }}

  - name: 'info-alerts'
    webhook_configs:
      - url: 'http://localhost:5001/info'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']
